version: "2"

run:
  tests: false
  timeout: 5m

formatters:
  enable:
    - goimports

linters:
  disable:
    - staticcheck
  enable:
    - bodyclose
    - goconst
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
