version: "2"

run:
  tests: false

formatters:
  enable:
    - goimports

linters:
  enable:
    - bodyclose
    - dupl
    - goconst
    - godot
    - godox
    - goprintffuncname
    - gosec
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013
  max-issues-per-linter: 0
  max-same-issues: 0
